AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  BucketName:
    Type: String
    Description: "Enter a unique name for your S3 bucket (3-63 characters, lowercase letters, numbers, hyphens, and no consecutive periods)"
    MinLength: 3
    MaxLength: 63
    AllowedPattern: "[a-z0-9]+(-[a-z0-9]+)*"
    ConstraintDescription: "Bucket name must be between 3 and 63 characters, use only lowercase letters, numbers, hyphens, and no consecutive periods."
  EncryptionType:
    Type: String
    Description: "Choose the type of encryption for the S3 bucket. Options: SSE-S3, SSE-KMS"
    Default: "SSE-S3"
    AllowedValues: ["SSE-S3", "SSE-KMS"]
  KMSKeyID:
    Type: String
    Description: "Enter the KMS Key ID for SSE-KMS encryption (optional)"
    ConstraintDescription: "Please enter a valid KMS Key ID."
  BucketOwnerTag:
    Type: String
    Description: "Tag for 'Bucket Owner'"
  CriticalityTag:
    Type: String
    Description: "Criticality level for the S3 bucket (Low or High)"
    AllowedValues: ["Low", "High"]
    ConstraintDescription: "Please choose a valid criticality level (Low or High)."
  EnvironmentTag:
    Type: String
    Description: "Environment tag for the S3 bucket"
    AllowedValues: ["PROD", "TST"]
    ConstraintDescription: "Please choose a valid environment (PROD or TST)."
  ProjectTag:
    Type: String
    Description: "Tag for 'Project'"
    ConstraintDescription: "Please enter a valid value for the Project tag."
  EnableVersioning:
    Type: String
    Description: "Enable versioning for the S3 bucket"
    Default: "No"
    AllowedValues: ["Yes", "No"]
  EnableLogging:
    Type: String
    Description: "Enable logging for the S3 bucket"
    Default: "No"
    AllowedValues: ["Yes", "No"]
  LogDestinationBucket:
    Type: String
    Description: "Destination bucket for S3 access logs (if logging is enabled)"

Conditions:
  UseKMS: !Equals [!Ref EncryptionType, "SSE-KMS"]
  UseVersioning: !Equals [!Ref EnableVersioning, "Yes"]
  UseLogging: !Equals [!Ref EnableLogging, "Yes"]

Resources:
  MyS3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref BucketName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              !If
                - UseKMS
                - KMSMasterKeyID: !Ref KMSKeyID
                  SSEAlgorithm: "aws:kms"
                - SSEAlgorithm: "AES256"
      Tags:
        - Key: "Environment"
          Value: !Ref EnvironmentTag
        - Key: "Project"
          Value: !Ref ProjectTag
        - Key: "BucketOwner"
          Value: !Ref BucketOwnerTag
        - Key: "Criticality"
          Value: !Ref CriticalityTag
      VersioningConfiguration:
        !If
          - UseVersioning
          - Status: "Enabled"
          - Status: "Suspended"
      LoggingConfiguration:
        !If
          - UseLogging
          - DestinationBucketName: !Ref LogDestinationBucket
            LogFilePrefix: !Sub "S3-logs-${BucketName}"
          - {}

  MyBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !GetAtt MyS3Bucket.Arn
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 's3:*'
            Effect: Allow
            Resource: 
              - !Sub 'arn:aws:s3:::${BucketName}/*'
              - !Sub 'arn:aws:s3:::${BucketName}'
            Principal: '*'


